/* tslint:disable */
require("./CreateDocument.module.css");
var styles = {
    createDocument: 'createDocument_bba1ddaa',
    teams: 'teams_bba1ddaa',
    alignCenter: 'alignCenter_bba1ddaa',
    divrow: 'divrow_bba1ddaa',
    divColumn1: 'divColumn1_bba1ddaa',
    divColumn2: 'divColumn2_bba1ddaa',
    divColumn3: 'divColumn3_bba1ddaa',
    divApprover: 'divApprover_bba1ddaa',
    divDate: 'divDate_bba1ddaa',
    modalButton: 'modalButton_bba1ddaa',
    modalHeading: 'modalHeading_bba1ddaa',
    wdthlft: 'wdthlft_bba1ddaa',
    wdthrgt: 'wdthrgt_bba1ddaa',
    wdthfrst: 'wdthfrst_bba1ddaa',
    wdthmid: 'wdthmid_bba1ddaa',
    wdthlst: 'wdthlst_bba1ddaa',
    mt: 'mt_bba1ddaa',
    '-ms-flex': 'flex_bba1ddaa',
    flex: 'flex_bba1ddaa',
    btn: 'btn_bba1ddaa',
    border: 'border_bba1ddaa',
    divLabel: 'divLabel_bba1ddaa',
    rgtalign: 'rgtalign_bba1ddaa',
    container: 'container_bba1ddaa',
    uploadDiv: 'uploadDiv_bba1ddaa',
    documentMainDiv: 'documentMainDiv_bba1ddaa',
    templateDiv: 'templateDiv_bba1ddaa',
    mandatory: 'mandatory_bba1ddaa',
    row: 'row_bba1ddaa',
    radioDiv: 'radioDiv_bba1ddaa',
    column: 'column_bba1ddaa',
    'ms-Grid': 'ms-Grid_bba1ddaa',
    title: 'title_bba1ddaa',
    subTitle: 'subTitle_bba1ddaa',
    description: 'description_bba1ddaa',
    button: 'button_bba1ddaa',
    label: 'label_bba1ddaa',
    marginLeft: 'marginLeft_bba1ddaa',
    testClass: 'testClass_bba1ddaa',
    welcome: 'welcome_bba1ddaa',
    welcomeImage: 'welcomeImage_bba1ddaa',
    links: 'links_bba1ddaa'
};
export default styles;
/* tslint:enable */ 
//# sourceMappingURL=CreateDocument.module.scss.js.map