import { WebPartContext } from "@microsoft/sp-webpart-base";

export interface IRevisionHistoryProps {
  description: string;
  timeLineColor: string;
  siteUrl: string;
  hubSiteUrl: string;
  hubSite: string;
  context: WebPartContext;
  DocumentRevisionLog: string;
  notificationPrefListName: string;
  documentApprovalSitePage: string;
  workflowDetailsListName: string;
  workflowHeaderListName: string;
  workflowTaskListName: string;
  sourceDocuments: string;
  documentIndexListName: string;
  taskDelegationListName: string;
  // project: string;
  statusColor: string;
  documentReviewSitePage: string;
  documentApprovalDateColor: string;
  documentCreatedDateColor: string;
  documentReviewedDateColor: string;
  workflowStartedDateColor: string;
  documentApprovalContentColor: string;
  documentCreatedContentColor: string;
  documentReviewedContentColor: string;
  workflowStartedContentColor: string;
  documentVoidDateColor: string;
  emailNoficationSettings: string;
  documentVoidContentColor: string;
  permissionMatrixSettings: string;
  accessGroupDetailsListName: string;
  departmentListName: string;
  bussinessUnitList: string;
  requestLaURL: string;
  internalTransittalConFab: string;
}

export interface IMessage {
  isShowMessage: boolean;
  messageType: number;
  message: string;
}

export interface IRevisionHistoryState {
  currentUserEmail: string;
  statusMessage: IMessage;
  currentUser: number;
  logItems: any[];
  documentName: string;
  documentIndexItems: any[];
  workflowDetailItems: any[];
  iframeModalclose: boolean;
  tableShow: string;
  tableinTimeLine: string;
  showModal: boolean;
  reviewed: string;
  workflowInitiated: string;
  workflowStatus: string;
  showReviewModal: boolean;
  showworkflowInitiatedModal: boolean;
  delegateUser: any;
  delagatePeoplePicker: string;
  dueDate: any;
  timelineElement: string;
  notificationPreference: string;
  criticalDocument: boolean;
  approverEmail: string;
  requestorEmail: string;
  ownerEmail: string;
  owner: string;
  requestor: string;
  approver: any;
  detailIdForApprover: any;
  documentID: string;
  revision: string;
  hubSiteUserId: any;
  delegatedFromId: any;
  delegatedToId: any;
  delegateToIdInSubSite: any;
  delegateToEmail: any;
  delegateForIdInSubSite: any;
  approverName: string;
  requestorDate: string;
  cancelConfirmMsg: string;
  confirmDialog: boolean;
  cancelledBy: string;
  reviewers: any[];
  divForSendRemainder: boolean;
  divForCancel: boolean;
  divForDelegation: boolean;
  workflowInitiatedVoid: string;
  showworkflowInitiatedVoidModal: boolean;
  delegateToTitle: string;
  delegatingLoader: string;
  timelineDisplay: string;
  ownerID: any;
  lengthOfReviwers: any;
  taskOwnerName: string;
  currentUserName: string;
}

export interface IRevisionHistoryWebPartProps {
  description: string;
  timeLineColor: string;
  siteUrl: string;
  hubSiteUrl: string;
  hubSite: string;
  context: WebPartContext;
  DocumentRevisionLog: string;
  notificationPrefListName: string;
  documentApprovalSitePage: string;
  workflowDetailsListName: string;
  workflowHeaderListName: string;
  workflowTaskListName: string;
  sourceDocuments: string;
  documentIndexListName: string;
  taskDelegationListName: string;
  //project: string;
  statusColor: string;
  documentReviewSitePage: string;
  documentApprovalDateColor: string;
  documentCreatedDateColor: string;
  documentReviewedDateColor: string;
  workflowStartedDateColor: string;
  documentApprovalContentColor: string;
  documentCreatedContentColor: string;
  documentReviewedContentColor: string;
  workflowStartedContentColor: string;
  documentVoidDateColor: string;
  emailNoficationSettings: string;
  documentVoidContentColor: string;
  permissionMatrixSettings: string;
  accessGroupDetailsListName: string;
  departmentListName: string;
  bussinessUnitList: string;
  requestLaURL: string;
  internalTransittalConFab: string;
}